DROP SCHEMA IF EXISTS OLAP
GO

CREATE SCHEMA OLAP
GO

CREATE VIEW OLAP.DATEDIMENSION AS
(
SELECT
	DATE
,	WEEKDAY
,	WEEKDAYNAME
,	MONTH
,	MONTHNAME
,	QUARTER
,	QUARTERNAME
,	YEAR
FROM
	DBO.DateDimension
);
GO

CREATE VIEW OLAP.CITY AS
(
SELECT 
	CITYID
,	CITYNAME
,	STATEPROVINCEID
,	CONVERT(VARCHAR,VALIDFROM, 23) VALIDFROM
,	CONVERT(VARCHAR,VALIDTO, 23) VALIDTO
FROM
	APPLICATION.CITIES
)
GO

CREATE VIEW OLAP.COUNTRY AS
(
SELECT 
	COUNTRYID
,	COUNTRYNAME
,	FORMALNAME
,	CONTINENT
,	REGION
,	SUBREGION
,	CONVERT(VARCHAR,VALIDFROM, 23) VALIDFROM
,	CONVERT(VARCHAR,VALIDTO, 23) VALIDTO
FROM
	APPLICATION.COUNTRIES
)
GO

CREATE VIEW OLAP.PROVINCES AS
(
SELECT
	STATEPROVINCEID
,	STATEPROVINCENAME
,	COUNTRYID
,	CONVERT(VARCHAR,VALIDFROM, 23) VALIDFROM
,	CONVERT(VARCHAR,VALIDTO, 23) VALIDTO
FROM
	APPLICATION.STATEPROVINCES
)
GO

CREATE VIEW OLAP.CUSTOMER AS
(
SELECT 
	CUSTOMERID
,	CUSTOMERNAME
,	DELIVERYCITYID CITYID
,	ACCOUNTOPENEDDATE
,	STANDARDDISCOUNTPERCENTAGE
,	PHONENUMBER
,	DELIVERYADDRESSLINE1+' '+DELIVERYADDRESSLINE2+' '+DELIVERYPOSTALCODE AS CUSTOMER_ADDRESS
,	POSTALADDRESSLINE1+' '+POSTALADDRESSLINE2+' '+POSTALPOSTALCODE AS POSTAL_ADDRESS
FROM
	SALES.CUSTOMERS
)
GO

CREATE VIEW OLAP.FACT_ORDERS AS
(
SELECT
	ORDERID
,	CUSTOMERID
,	ORDERDATE
,	EXPECTEDDELIVERYDATE
,	CUSTOMERPURCHASEORDERNUMBER
FROM
	SALES.ORDERS
)
GO

CREATE VIEW OLAP.INVOICES AS
(
SELECT
	INVOICEID
,	CUSTOMERID
,	ORDERID
,	INVOICEDATE
,	CUSTOMERPURCHASEORDERNUMBER
,	DELIVERYINSTRUCTIONS
,	TOTALDRYITEMS
,	TOTALCHILLERITEMS
,	CONVERT(VARCHAR,CONFIRMEDDELIVERYTIME, 23) DELIVERYDATE
,	CONFIRMEDRECEIVEDBY
FROM
	SALES.INVOICES
)
GO



-- PROBLEMATYCZNY WIDOK - NULLE DO OBSLUZENIA
CREATE VIEW OLAP.FACT_SPECIALDEALS AS
(
SELECT
	SPECIALDEALID
,	STOCKITEMID
,	CUSTOMERID
,	DEALDESCRIPTION
,	STARTDATE
,	ENDDATE
,	DISCOUNTPERCENTAGE
FROM
	SALES.SPECIALDEALS
)
GO
